/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "asociacion.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

estado *
ponerasociacion_1(int id, char *clave, char *valor,  CLIENT *clnt)
{
	ponerasociacion_1_argument arg;
	static estado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.id = id;
	arg.clave = clave;
	arg.valor = valor;
	if (clnt_call (clnt, ponerAsociacion, (xdrproc_t) xdr_ponerasociacion_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_estado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

valor_estado *
obtenerasociacion_1(int id, char *clave,  CLIENT *clnt)
{
	obtenerasociacion_1_argument arg;
	static valor_estado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.id = id;
	arg.clave = clave;
	if (clnt_call (clnt, obtenerAsociacion, (xdrproc_t) xdr_obtenerasociacion_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_valor_estado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

estado *
borrarasociacion_1(int id, char *clave,  CLIENT *clnt)
{
	borrarasociacion_1_argument arg;
	static estado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.id = id;
	arg.clave = clave;
	if (clnt_call (clnt, borrarAsociacion, (xdrproc_t) xdr_borrarasociacion_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_estado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

enumerados *
enumerar_1(int id,  CLIENT *clnt)
{
	static enumerados clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, enumerar,
		(xdrproc_t) xdr_int, (caddr_t) &id,
		(xdrproc_t) xdr_enumerados, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
