/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "asociacion.h"

bool_t
xdr_tupla (XDR *xdrs, tupla *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->clave, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->valor, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->siguiente, sizeof (tupla), (xdrproc_t) xdr_tupla))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lista (XDR *xdrs, lista *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->lista_tupla, sizeof (tupla), (xdrproc_t) xdr_tupla))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->siguiente, sizeof (lista), (xdrproc_t) xdr_lista))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_estado (XDR *xdrs, estado *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_valor_estado (XDR *xdrs, valor_estado *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->valor, ~0))
		 return FALSE;
	 if (!xdr_estado (xdrs, &objp->Estado))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tupla_unica (XDR *xdrs, tupla_unica *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->clave, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->valor, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_enumerados (XDR *xdrs, enumerados *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->tupla.tupla_val, (u_int *) &objp->tupla.tupla_len, ~0,
		sizeof (tupla_unica), (xdrproc_t) xdr_tupla_unica))
		 return FALSE;
	 if (!xdr_estado (xdrs, &objp->Estado))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ponerasociacion_1_argument (XDR *xdrs, ponerasociacion_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->clave, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->valor, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_obtenerasociacion_1_argument (XDR *xdrs, obtenerasociacion_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->clave, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_borrarasociacion_1_argument (XDR *xdrs, borrarasociacion_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->clave, ~0))
		 return FALSE;
	return TRUE;
}
